<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Customer Email</name>
   <tag></tag>
   <elementGuidId>7510b02a-7dbb-4150-8d62-19bc31f4101e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CustomerEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CustomerEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd735072-71c3-4022-a740-fc43b1832d03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>6e35214c-73b2-40c2-8085-483b1c81a0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer[email]</value>
      <webElementGuid>0f536129-89bb-442b-abf7-f5776d759658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CustomerEmail</value>
      <webElementGuid>8293313e-b539-4b01-919a-52a8eb9cfca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-full</value>
      <webElementGuid>c9523af7-897f-4d56-8d89-24c2347680a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b00d7d98-ced1-48ed-a44b-e2d7287bd6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CustomerEmail&quot;)</value>
      <webElementGuid>4267914b-067d-4efe-82f6-3bd2e7aeba62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CustomerEmail']</value>
      <webElementGuid>5032eab3-24ce-4b08-bf1e-3761ec9990e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/input[3]</value>
      <webElementGuid>d67a8a26-7bd5-457b-b418-5a7e8c80a28b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/input[3]</value>
      <webElementGuid>a05f7848-011d-4dcb-ac9e-4831ceab3b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'customer[email]' and @id = 'CustomerEmail']</value>
      <webElementGuid>3106e332-e184-4952-8dfa-066f9f8233d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
