<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_VTG V.2 LO Black OW</name>
   <tag></tag>
   <elementGuidId>7ca7f2c7-40a7-47fc-a46a-f2c54d4f615c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CollectionAjaxContent']/div/div/div/a/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.grid-product__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ab6e527a-81e7-429e-914e-9ee93e7488d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>grid-product__title</value>
      <webElementGuid>d0b75b16-756a-4844-aa72-969708022098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VTG V.2 LO Black OW</value>
      <webElementGuid>d75ff5b8-a14e-4d0a-a37b-f2f4feca4c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CollectionAjaxContent&quot;)/div[@class=&quot;grid grid--uniform grid--scattered-large-3 grid--scattered-small-1&quot;]/div[@class=&quot;grid__item grid-product grid-product--padded medium-up--one-third aos-init aos-animate&quot;]/div[@class=&quot;grid-product__content&quot;]/a[@class=&quot;grid-product__link quick-product__btn js-screen-open-product-6183822688447 js-no-transition&quot;]/div[@class=&quot;grid-product__meta&quot;]/div[@class=&quot;grid-product__title&quot;]</value>
      <webElementGuid>059389ee-8902-4bb0-9636-8ab7f3d6397a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CollectionAjaxContent']/div/div/div/a/div[2]/div</value>
      <webElementGuid>9b166962-da20-41a5-99c9-1bd2f2aa4051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 429.000,00'])[1]/following::div[44]</value>
      <webElementGuid>f4c25fea-d329-4782-8a38-888c39151cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 0,00'])[1]/following::div[44]</value>
      <webElementGuid>35dc03d7-1ce8-41e9-85e0-a1d086980099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 395.000,00'])[1]/preceding::div[1]</value>
      <webElementGuid>ee3457a2-9239-473c-81c4-1e01d93f3a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VTG V.2 LO Black OW']/parent::*</value>
      <webElementGuid>506d154c-e8cf-4879-a869-c69497b43848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]/div</value>
      <webElementGuid>316a1a29-cd2f-4438-afbc-4d9f73e3192d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'VTG V.2 LO Black OW' or . = 'VTG V.2 LO Black OW')]</value>
      <webElementGuid>ebfb4f3b-6237-48bc-86b9-48dd25bbacf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
