<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Item</name>
   <tag></tag>
   <elementGuidId>df76a953-01c4-4a8b-893a-44f943acceab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='amasty-shopby-product-list']/div[3]/ol/li/div/a/span/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.product-image-photo.lazyloaded</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e676feee-e31b-4125-815a-56aa8a920259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-image-photo lazyloaded</value>
      <webElementGuid>2cffb616-dc13-407e-a027-dba5a4118893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.matahari.com/media/catalog/product/8/1/81460102_1.jpg?optimize=medium&amp;fit=bounds&amp;height=379&amp;width=293</value>
      <webElementGuid>1b5cef59-05ab-4134-9cd3-4d2e1c74ad14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.matahari.com/media/catalog/product/8/1/81460102_1.jpg?optimize=medium&amp;fit=bounds&amp;height=379&amp;width=293</value>
      <webElementGuid>0395506c-a1fb-419d-bcf2-7cdb49f31d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-width</name>
      <type>Main</type>
      <value>293</value>
      <webElementGuid>eb8cc685-d279-40cb-860d-8d4ad128b0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max-height</name>
      <type>Main</type>
      <value>379</value>
      <webElementGuid>f8a67651-4140-44be-bb9e-da98c2ede906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Yongki Komaladi Tassel Flat Shoes Wanita</value>
      <webElementGuid>ca90fec0-13c7-4c56-a3b4-464b9404f148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amasty-shopby-product-list&quot;)/div[@class=&quot;products wrapper grid products-grid&quot;]/ol[@class=&quot;products list items product-items&quot;]/li[@class=&quot;item product product-item&quot;]/div[@class=&quot;product-item-info&quot;]/a[@class=&quot;product photo product-item-photo product-item-click&quot;]/span[@class=&quot;product-image-container&quot;]/span[@class=&quot;product-image-wrapper&quot;]/img[@class=&quot;product-image-photo lazyloaded&quot;]</value>
      <webElementGuid>94e5bc08-9a02-4e4c-a5cb-6f3c804bf8d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amasty-shopby-product-list']/div[3]/ol/li/div/a/span/span/img</value>
      <webElementGuid>81f66441-a61b-433e-9dd6-fec5efead5a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Yongki Komaladi Tassel Flat Shoes Wanita']</value>
      <webElementGuid>a3fcfeca-e4be-482d-a0eb-65864d7f6f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>95a8952e-43fb-4653-a767-4f417b042cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.matahari.com/media/catalog/product/8/1/81460102_1.jpg?optimize=medium&amp;fit=bounds&amp;height=379&amp;width=293' and @alt = 'Yongki Komaladi Tassel Flat Shoes Wanita']</value>
      <webElementGuid>6c52d287-fb02-476b-aba4-19801201c7ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
