<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tambah Ke Keranjang</name>
   <tag></tag>
   <elementGuidId>69c08f82-f6c2-42a4-b808-9b257ede9901</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='product-addtocart-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-addtocart-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f0c7a135-2c56-4b7d-81cd-e1dcbf2225b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9292a57a-5032-4ee8-bc70-49b9449cffc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tambah ke keranjang</value>
      <webElementGuid>1f9fd28f-8c9c-45f2-8518-70d40d1a445d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action primary tocart</value>
      <webElementGuid>d3f01ffd-25f7-4b2c-a673-e577ff108c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-addtocart-button</value>
      <webElementGuid>d724d70a-9195-495b-b28e-d60b50e28103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tambah ke keranjang</value>
      <webElementGuid>bc3d9853-cc49-4ec4-97fa-c44427987aef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-addtocart-button&quot;)</value>
      <webElementGuid>2e260deb-4e16-481b-ab68-63570e755425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='product-addtocart-button']</value>
      <webElementGuid>a9026165-acbd-4cef-97e3-26a14c6ba395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_addtocart_form']/div[2]/div/div[3]/div/div[2]/button</value>
      <webElementGuid>97353ff7-0240-4a5c-92e4-e1f233dcdb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='barang'])[1]/following::button[1]</value>
      <webElementGuid>43507908-ccbc-4d78-8691-9249194252da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambahkan ke Daftar Keinginan'])[1]/following::button[1]</value>
      <webElementGuid>caa4a93e-0516-438d-97c3-dd33e6484a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pergi Ke Keranjang'])[1]/preceding::button[1]</value>
      <webElementGuid>bfbf3086-e4b2-4b2a-a8ec-509a14a2399a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/button</value>
      <webElementGuid>e05662e1-9985-4a5e-90c1-67c34d36aa36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @title = 'Tambah ke keranjang' and @id = 'product-addtocart-button' and (text() = 'Tambah ke keranjang' or . = 'Tambah ke keranjang')]</value>
      <webElementGuid>76ca3baf-dcba-4c71-b48a-1ab2c026615f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
