<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_38</name>
   <tag></tag>
   <elementGuidId>0cb23fbb-65f4-46cb-b2e4-52d5f2592080</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-label-size-558-item-16458</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='option-label-size-558-item-16458']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>65398eb9-f9c9-4a17-a303-67ca7b7c1bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option text</value>
      <webElementGuid>eb48287d-bb98-468e-890a-912b459e6723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-size-558-item-16458</value>
      <webElementGuid>8e485e0a-65ea-45d8-846a-dfb729c5392f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4986cf48-c4c9-4f4c-a876-cf3e29425c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5e1252c5-11a0-44fa-8d06-08ecde2f5ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>option-label-size-558</value>
      <webElementGuid>1f41fe7f-e911-4201-9000-121fb456644d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>94c6f2e3-ba16-4679-980f-ca4e58476caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>61d8c8f1-b804-4713-a0ba-b24550286b6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-id</name>
      <type>Main</type>
      <value>16458</value>
      <webElementGuid>3f43a345-3bcb-4621-a666-d50e0b020280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-label</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>cfe11074-c466-4535-a5fc-5fe4b566b5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>5bee8bdc-1ca0-48e1-afbc-0ff8c4f05ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8cc9a4eb-9a9b-4a3d-86f6-4ba6cadd0acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thumb-width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>96e37a2b-ae10-427a-81ac-f90d2330063b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thumb-height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>4d683cb1-6dc8-4473-baa4-87dc43a8078a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-tooltip-value</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>611d30f7-dc1d-4ce0-b227-b3db15039ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>793a7ff8-c24b-4507-a2aa-c4d701fda74b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-label-size-558-item-16458&quot;)</value>
      <webElementGuid>fb180437-e6fe-49b0-b454-ddab75be4281</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='option-label-size-558-item-16458']</value>
      <webElementGuid>d67cc604-081c-4e38-87da-a793c8a6bdf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div/div/div[3]</value>
      <webElementGuid>2397db78-d477-4085-833f-752431e9c661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih Ukuran'])[1]/following::div[4]</value>
      <webElementGuid>4991e27d-6419-4612-9194-5c27927f71f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bayar dalam 30 hari 0% Rp 211.800 / bulan.'])[1]/following::div[9]</value>
      <webElementGuid>857c5ece-86d2-4e67-a8d2-afc1c54445bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warna Terpilih'])[1]/preceding::div[4]</value>
      <webElementGuid>ad9fb1ce-d013-4d2a-8701-d9caba017eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BROWN'])[1]/preceding::div[4]</value>
      <webElementGuid>af46665c-b5d3-486c-8448-8f92aa0a6ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div[3]</value>
      <webElementGuid>3273429c-da75-4c90-ad06-eab6687f62c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'option-label-size-558-item-16458' and (text() = '38' or . = '38')]</value>
      <webElementGuid>b60c5570-7cdf-4850-9856-b8232efef664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
